---
name: Jekyll

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundle-cache: true # Package app's gems into the vendor/cache directory
        ruby-version: 2.7 # Specify the Ruby version you want to use

    - name: Install dependencies
      run: bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Upload site as artifact
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: _site
